# Generated by Django 5.0.4 on 2024-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(default=None, max_length=15, verbose_name='post id'),
        ),
    ]
