# Generated by Django 5.0.4 on 2024-04-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(default=None, verbose_name='post id'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
