# Generated by Django 5.0.4 on 2024-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_commentary_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(verbose_name='post id'),
        ),
    ]
