# Generated by Django 5.0.4 on 2024-05-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_like',
        ),
    ]
