version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    depends_on:
      - db


  telegrambot:
    build:
      context: ./posts/services.py
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env